MODIFIED: App.jsx HeroBanner.tsx, PetSliderCarousel.tsx, SearchPets.t…
Code-the-Dream-School/ffprac-team3-front pull request #42
Opened 2024-04-12 01:17 UTC by wessstt

**Footer** 
- Added to all routes & remove API callout 

**App.jsx**
- Fixed "Uncaught (in promise) TypeError" using a try-catch block / 

**HeroBanner**
- Added an about 
- Added Button click to go to all pets
- Added handles for the search bars on home page by keyword and location (location isnt working - has a bug somewhere) 

**SearchPets:** 
- Fixed State Filters now they only display available states as filters change it adjusts 
- Added breed filters
- Updated age filter to age groups
- Added Favorites filter

**petData**
- Added all pet breeds in their own files so all breed filters have data. 

**other**
- Adjusted styling on pages as needed.

2024-04-12 18:31 UTC, Leonardo-Reyes-Munoz commented on src/App.jsx
Nice addition of the try catch block to prevent an error. Once we connect to the API, that error will hopefully go away.

2024-04-12 18:32 UTC, Leonardo-Reyes-Munoz commented on src/components/HeroBanner.tsx
The larger font on the Hero banner looks great.

I really like the description :-)

2024-04-12 18:35 UTC, Leonardo-Reyes-Munoz commented on src/components/SearchPets.tsx
I was not able to reproduce the bug you had mentioned by just clicking around the search implementation. I would love to take a closer look to see if I can help. Can you provide more information on the bug you were running into? Were you getting any errors in your console? Steps on reproducing the bug may also be helpful in narrowing down where it may be coming from :-)

2024-04-12 21:50 UTC, Count-MonteCristo requested changes
Everything looks/works great with the exception of the bug you mentioned.

For instance, while on the home page, I searched for a pet in "North Carolina" and "NC", but neither returned any results.

However, when I used the filter on the search page, it works as intended.

My suggestion is to pass the value from the location search bar on the home page to the filter on the search page. So if someone types NC in the location search bar, it will auto-populate the location filter on the next page.

I do see that it's already on the page URL, so an easy way would be to check for URL params, and use them if they're present:

<img width="485" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team3-front/assets/79714613/2b65e8ba-451f-48fc-9c88-6e80d8befac9">

2024-04-16 14:57 UTC, Count-MonteCristo approved these changes

2024-04-17 22:46 UTC, wessstt commented
Had to reopen to push unmerged commits. Was getting a error so had to troubleshoot that. All is right in the universe again. 😂

2024-04-17 22:54 UTC, merged